version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:80' 
  storybook:
    build:
      context: ./
      target: storybook
      dockerfile: Dockerfile
    ports:
      - '8080:9009' 