version: "3.8"

services:
  web:
    build: 
      context: ./
      target: web
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
  storybook:
    build: 
      context: ./
      target: storybook
      dockerfile: Dockerfile.dev
    command: yarn storybook
    volumes:
      - ./:/app
    ports:
      - '9009:9009'